version: 2
jobs:
  build:
    docker:
      - image: unpause/gpp:7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: build tests
          command: |
            pushd test
            make
            popd
      - run:
          name: run tests
          command: |
            pushd test
            make test
            popd
