version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt-get -y update; true
            sudo apt-get install -y apt
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo apt-get -y update; true
            sudo apt-get install -y gcc-5 g++-5
      - run:
          name: build tests
          command: |
            pushd test
            make
            popd
      - run:
          name: run tests
          command: |
            pushd test
            make test
            popd
